# Write your imports here

def food_to_price(food_list: list) -> str:
    """
    We want to create a dictionary of with food items and the price of the food.
    The first item in the list is worth 1 kr. All other items are worth the previous
    list item's price * 1.1.

    Return a dictionary will the following format:
    {<food item>: <price>, <food item>: <price>, ...}

    Examples
    ---------
    1)
    function_input:
        food_list = ["apple", "meat", "bread", "grillkrydda"]

    function_output:
        {"apple": 1, "meat": 1.1, "bread": 1.21, "grillkrydda": 1.33}
    """
    pass # Implement the function here, remove pass


def csv_to_dict(csv_string: str) -> dict:
    """
    We have a csv string (comma separated value) with multiple
    lines of usernames and services. A line has the following format:

    <username>;<usage>

    We want to create a password for each username and also map each username
    to a password. This can be accoplished by using a dictionary which will
    return the value of the function. In other words the dictionary
    should look like:

    {<username>: <generated password>, <username>: <generated password>, ...}

    a randomly generated password can be generated by the function generate_password().
    This function can be found in the helper_functions module (Needs to be imported).
    We do not care about the <usage> string in the csv file.

    Examples
    ---------
    1)
    function_input:
        csv_string = "clip_master;YouTube\n
                      tweet_legend;Twitter\n
                      aim_god;Steam \n

    function_output:
        {clip_master: 6ubmia6exsf, tweet_legend: hk2l5kmi30slqdpjreb, aim_god: iph7t5clt03i8uo}

    HINT:
        The .split() method for strings is useful when getting all substrings separated by a character (like \n, or ;)
        "hello_world".split("_") will return ["hello", "world"] as an example. See help("".split) for more details.
    """
    pass # Implement the function here, remove pass

if __name__ == "__main__":
    # Test your code here

    print(food_to_price(["apple", "meat", "bread", "grillkrydda"]))
    # print(csv_to_dict("clip_master;YouTube\ntweet_legend;Twitter\naim_god;Steam"))
